modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="seedcrackerx"
version="${file.jarVersion}"
displayName="Seed Cracker X"
authors="KaptainWutax, 19MisterX98, thePlaceholder"
description='''Used for finding the seed of multiplayer or singleplayer worlds.'''

[[dependencies.seedcrackerx]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.seedcrackerx]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
